# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yulebaby' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yulebaby
  pod 'Moya'
  pod 'SwiftyJSON'
  pod 'Kingfisher', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'  
  pod 'Proposer'
  pod 'ImageViewer'
  pod 'Reusable'
  pod 'MBProgressHUD'
  pod 'ReachabilitySwift'
  pod 'EmptyDataSet-Swift'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Toast-Swift', '~> 3.0.1'
  #  pod 'Log'
  pod 'CryptoSwift'
  pod 'SwiftyAttributes'
  pod 'AsyncSwift'
  pod 'MJRefresh'
  pod 'EmptyDataSet-Swift'
  pod 'XCGLogger', '~> 6.0.2'
  target 'yulebabyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yulebabyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
